### ISSUE TITLE
get some data

### ISSUE THREAD

**Issue by jspaaks** [matchms/notebooks#4]
e.g. ``gnpslibraryjson_filtered.json`` used [here](https://github.com/matchms/notebooks/blob/aec003683a5e386066fb836281e417875b0336e8/matchms_01_MGF_from_gnps_library_search.ipynb).

**Comment by jspaaks** [comment]
I'm adding some data here https://github.com/matchms/notebooks/pull/12

**Comment by CunliangGeng** [comment]
https://github.com/matchms/notebooks/pull/12 is approved, this issue can be closed.
