### ISSUE TITLE
change "spec2vec" to "matchms" in the notebooks' content

### ISSUE THREAD

**Issue by CunliangGeng** [matchms/notebooks#6]

**Comment by jspaaks** [comment]
Hanno and I decided to simplify the notebooks for now, while the matchms library is undergoing extensive changes to its layout. The one notebook that is still there (https://github.com/matchms/notebooks/blob/689c72840651b01773da039acabd955a6b4cd7dc/tutorial.ipynb) only talks about matchms, never spec2vec, and uses matchms only in its new layout (https://github.com/matchms/matchms/pull/47).

This issue can be closed.

**Comment by CunliangGeng** [comment]
Thanks.

**Comment by jspaaks** [comment]
I forgot to mention we did still keep the 'old' notebooks, they are on the ``parked`` branch.
